### ISSUE TITLE
Getting subscriptionId not by taskParams, but by credential 

### ISSUE THREAD

**Issue by yuhattor** [Azure/aca-deploy#4]
Getting subscriptionId not by taskParams, but by credential 
https://github.com/Azure/aca-deploy/blob/08f4b497c50929376c33d7b1c2d7c8ad0d8faff7/src/main.ts#L25-L26

This is implemented like below in aci-deploy action.
We use ```DefaultAzureCredential()``` from ```@azure/identity``` instead ```TokenCredential**s**()``` from ```@azure/ms-rest-js```, and need to find a way to specify it

https://github.com/Azure/aci-deploy/blob/85ab82e201431dfa391377c0084be2e9e08c535e/src/taskparameters.ts#L36-L38

**Comment by ry0y4n** [comment]
#21

**Comment by yuhattor** [comment]
will close this issue:)
