### ISSUE TITLE
GitHub Actions Parameters Validation

### ISSUE THREAD

**Issue by yuhattor** [Azure/aca-deploy#6]
Related to 👉 Finding a way to pass associative array to YAML #5

Even if yaml or json is eventually adopted, the values need to be validated. In particular, what value should be set? Are there any exclusive settings? and so on should be verified and sent out as an error.

https://github.com/Azure/aca-deploy/blob/08f4b497c50929376c33d7b1c2d7c8ad0d8faff7/src/taskparameters.ts#L67-L71

**Comment by ry0y4n** [comment]
https://github.com/Azure/aca-deploy/pull/18

**Comment by ry0y4n** [comment]
#19

**Comment by ry0y4n** [comment]
#20
