### ISSUE TITLE
Prettify the output of the Actions

### ISSUE THREAD

**Issue by yuhattor** [Azure/aca-deploy#7]
For now, the action only output raw params and is needed to be prettify it.

- For GitHub Actions' debug output, we need to use ```core.debug()``` instead of ```console.log()``` . I had an error in ```core.debug()``` in an early implementation, so I temporarily used ```console.log()```, but this needs to be reverted
- For GitHub Actions general output, we shouldn't print the result of ```await client.containerApps.beginCreateOrUpdateAndWait()``` directly.

https://github.com/Azure/aca-deploy/blob/08f4b497c50929376c33d7b1c2d7c8ad0d8faff7/src/main.ts#L75-L82

**Comment by ry0y4n** [comment]
#22
